# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the index of the maximum value of each row in a matrix.
#'
#' @param m Numeric matrix
#'
#' @return A numeric vector containing the index for each row.
#' @export
MaxCol <- function(m) {
    .Call('_gpsFISH_MaxCol', PACKAGE = 'gpsFISH', m)
}

